# Generated by Django 4.0.3 on 2022-04-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verfarmapp', '0003_alter_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
