# Generated by Django 4.0.3 on 2022-04-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verfarmapp', '0004_remove_post_images_remove_post_slug_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesofVerticalFarming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, unique=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LeadersofVerticalFarming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, unique=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
