# Generated by Django 4.0.3 on 2022-04-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verfarmapp', '0006_whatisverticalfarming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadersofverticalfarming',
            name='title',
            field=models.CharField(blank=True, max_length=10000, unique=True),
        ),
    ]
